/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theofilin;

import ij.process.ImageProcessor;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingWorker;
import org.encog.neural.networks.BasicNetwork;
import org.encog.persist.EncogDirectoryPersistence;

/**
 *
 * @author noxymon
 */
public class Utama extends javax.swing.JFrame {

    /**
     * Creates new form Utama
     */
    
    static GraphicsDevice screen = GraphicsEnvironment.getLocalGraphicsEnvironment().getScreenDevices()[0];
    static String path;
    
    public Utama() {
        initComponents();
    }

    static ImageProcessor ip;
    private Analyze analys;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdAnalyze = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        lblLoading = new javax.swing.JLabel();
        lblProg = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cmdReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblImage = new javax.swing.JLabel();
        lblGrade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Theofilin");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(480, 350));
        setMinimumSize(new java.awt.Dimension(480, 350));
        setResizable(false);

        cmdAnalyze.setText("Start");
        cmdAnalyze.setMaximumSize(new java.awt.Dimension(114, 42));
        cmdAnalyze.setMinimumSize(new java.awt.Dimension(114, 42));
        cmdAnalyze.setPreferredSize(new java.awt.Dimension(114, 42));
        cmdAnalyze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAnalyzeActionPerformed(evt);
            }
        });

        jLabel1.setText("Result :");

        lblResult.setBackground(new java.awt.Color(2, 23, 253));
        lblResult.setForeground(new java.awt.Color(254, 254, 254));
        lblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResult.setText("-");
        lblResult.setOpaque(true);

        lblLoading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ezgif.com-gif-maker.gif"))); // NOI18N
        lblLoading.setVisible(false);

        lblProg.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblProg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProg.setText("-");
        lblProg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setText("Analyze !");
        jButton1.setMaximumSize(new java.awt.Dimension(114, 42));
        jButton1.setMinimumSize(new java.awt.Dimension(114, 42));
        jButton1.setPreferredSize(new java.awt.Dimension(114, 42));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmdReset.setText("Exit");
        cmdReset.setMaximumSize(new java.awt.Dimension(114, 42));
        cmdReset.setMinimumSize(new java.awt.Dimension(114, 42));
        cmdReset.setPreferredSize(new java.awt.Dimension(114, 42));
        cmdReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdResetActionPerformed(evt);
            }
        });

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setMaximumSize(new java.awt.Dimension(500, 500));
        lblImage.setMinimumSize(new java.awt.Dimension(500, 500));
        lblImage.setName(""); // NOI18N
        lblImage.setPreferredSize(new java.awt.Dimension(500, 500));
        lblImage.setSize(500,500);
        jScrollPane1.setViewportView(lblImage);

        lblGrade.setBackground(new java.awt.Color(2, 23, 253));
        lblGrade.setForeground(new java.awt.Color(254, 254, 254));
        lblGrade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrade.setText("-");
        lblGrade.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLoading)
                        .addGap(18, 18, 18)
                        .addComponent(lblProg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdAnalyze, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblGrade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(cmdAnalyze, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdReset, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLoading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdResetActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_cmdResetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.setEnabled(false);
        CameraApps.StopCamera();
        CameraApps.GrabCamera(lblImage, 500,500);
        ip = CameraApps.ip;

        analys = new Analyze();
        analys.execute();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmdAnalyzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAnalyzeActionPerformed
        try {
              CameraApps.StartCamera(lblImage, 500, 500);
            } catch (IOException ex) {
            Logger.getLogger(Utama.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_cmdAnalyzeActionPerformed
    
    public class Analyze extends SwingWorker<Void, Void>{                
        @Override
        public Void doInBackground() throws Exception {
            clsColor.GetFiturAVG(ip, lblProg, lblLoading);
            lblResult.setText("Kelas " + EncogML.Hitung(clsColor.fitur));
            lblGrade.setText("Grade " + EncogTekstur.Hitung(clsColor.texture));
            
            String konten;
            DecimalFormat df = new DecimalFormat("#.######");
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            Date date = new Date();
            konten = dateFormat.format(date) + "," + "Encog Output" + "," + df.format(EncogML.hasil1) + "," + df.format(EncogML.hasil2)  + "," + df.format(EncogTekstur.hasil1)  + "," + df.format(EncogTekstur.hasil2)  + "," + df.format(EncogTekstur.hasil3)  + "," + df.format(EncogTekstur.hasil4)  + "," + df.format(EncogTekstur.hasil5) + "," + df.format(EncogTekstur.hasil6) + "," + df.format(EncogTekstur.hasil7);
            clsLog.write(konten);
            
            return null;
        }
        
        public void done(){
            CameraApps.mulailagi();
            jButton1.setEnabled(true);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        try {
            path = new File(".").getCanonicalPath();
            EncogML.ReadConfig(path + "/config.cfg");
            EncogTekstur.ReadConfig(path + "/config.cfg");
            EncogML.ML = (BasicNetwork)EncogDirectoryPersistence.loadObject(new File(EncogML.EnginePath));
            EncogTekstur.ML = (BasicNetwork)EncogDirectoryPersistence.loadObject(new File(EncogTekstur.TextureEnginePath));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Utama.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex){
            Logger.getLogger(Utama.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Utama frm = new Utama();
                screen.setFullScreenWindow(frm);
                frm.pack();
                frm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAnalyze;
    private javax.swing.JButton cmdReset;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblProg;
    private javax.swing.JLabel lblResult;
    // End of variables declaration//GEN-END:variables
}
